### PR TITLE
Overflowing Location Bug

### LINKED ISSUE #383: UI Overflow on locations
I see an overflow of the location here. I think this is particularly to do with the location- maybe there is a hardcoded size somewhere for overflow? Only seems to be a problem just when the location overflows and not other fields.

Image

Check it out on the BoG sprint 3 branch

### PR DESCRIPTION
**Pull request by DanielChee**
### Summary

Resolves #383

Fixes overflow state for recurring events that are too small. excluded location on desktop and mobile

### How to Test
Copy Uma's exact location here:
image

make sure it doesn't overflow

play around with other times in desktop and mobile to make sure it doesn't overflow.

### CODE REVIEW

File: src/components/TimeBlocks/index.tsx [hunk 1]
```diff
@@ -272,11 +271,21 @@ function MeetingDayBlock({
...
-              <span className={content.className} key={`content-body-${i}`}>
-                {content.content}
-              </span>
-            ))}
+            {contentBody.map((content, i) => {
+              const name = String(content.className).toLowerCase();
+              const isLocation = name === 'location' || name === 'where';
+              const isMobile =
+                typeof window !== 'undefined' &&
+                window.matchMedia('(max-width: 768px)').matches;
```
Comment (uma-anand) [inline src/components/TimeBlocks/index.tsx]: We want to separate business logic and styling. Don't bring in any checks here especially no magic numbers. Everything should be in the CSS.

File: src/components/TimeBlocks/index.tsx [hunk 2]
```diff
@@ -272,11 +271,21 @@ function MeetingDayBlock({
...
+              if (isLocation && period.end - period.start <= 30) return null;
+              if (isMobile && isLocation && period.end - period.start <= 49)
```
Comment (uma-anand) [inline src/components/TimeBlocks/index.tsx]: Do all this in the CSS hiding stuff only when the rendered block height is physically too small.

You could do something like this:
```
/* If block is too short, hide location entirely */
@container (max-height: 50px) {
  .meeting-wrapper .location,
  .meeting-wrapper .where {
    display: none;
  }
```

**Review by uma-anand — CHANGES_REQUESTED** [review]

**Comment by uma-anand** [comment]
I also think that this shouldn't be allowed, where the "pm" is half covered. Either overflow should be specified or the line shouldn't be there.
image

**Review by uma-anand — APPROVED** [review]
LGTM! Thanks for fixing this
